### PR TITLE
Delete orgunit enhancements

### PR DESCRIPTION
**Pull request by Bekkalizer**
Added some missing deletes and renamed the delete_site_with_data-> delete_orgunit_with_data
Added new function delete_orgunittree_with_data

### CODE REVIEW

**Comment by Bekkalizer** [comment]
Me and @oysteinga have tested the functions a bit on a tracker-focused database. The aggregate part of the scripts is not changed from the original delete_site_with_data.

**Comment by jason-p-pickering** [comment]
@Bekkalizer @oysteinga I am still not in favor of having both of these functions. Is there really a need for both of them?

**Comment by Bekkalizer** [comment]
The reason I started digging into this again was that @oysteinga needed to delete the whole orgunit tree in a database containing a lot of other things. Not sure if you meant to propose that we only need the recursive script(delete orgunittree), or if we only need the leaf-node delete(delete orgunit)?

The original change I made was making a parameter for recursion in the delete_site_with_data. I thought having two functions was your suggestion @jason-p-pickering - to minimize the dangers of people deleting more orgunits than they intended. Perhaps I misunderstood what you meant back then?

**Comment by jason-p-pickering** [comment]
@Bekkalizer Let me clarify. I see the need for two scripts, but without the very repetitive code between them. As I would see it, one script would delete a single site at the terminal branch of of the tree only. The other function would perform the recursive deletion, starting at the terminal branch, deleting all of those sites, and move its way upwards. It would be called with a UID of the orgunit whose branch (and self) should be deleted. 

It just seems right now there is a lot of duplication between the two scripts which may make maintenance and testing more difficult.

**Comment by Bekkalizer** [comment]
I thought it a bit impractical that the scripts was dependent on one another?

**Comment by jason-p-pickering** [comment]
@Bekkalizer I do not see this really as an intrinsic problem per se. It should be clear from the source that the recursive script would depend on the atomic script 
For me its really about separation of concerns. One which performs the deletion of a single orgunit, and one script which calls that script recursively.  I see the long-term maintenance as a much bigger hassle of two very similar, but slightly different scripts, but that is how I see it.

**Comment by Bekkalizer** [comment]
Yeah, I just thought it was nice with self-sustained scripts, and on the spot weighed that heavier than the maintenance issue. I have officially spent more time in this chat than actually writing the recursive script :) The actual delete statements in the scripts is the same, so its an easy update that I can make before eventually merging the branch.

**Comment by jason-p-pickering** [comment]
@Bekkalizer I am not in favor of the approach, but understand and its your call.

**Comment by Bekkalizer** [comment]
@jason-p-pickering - I'll merge this for now, someone asked for a bulk delete on the list. Ill pick up making a version with a common core the next time I need to delete orgunits.

**Pull request merged**
