### PR TITLE
Added option to recurse and some missing delete statements on tracker data

### PR DESCRIPTION
**Pull request by Bekkalizer**

### CODE REVIEW

**Comment by jason-p-pickering** [comment]
@Bekkalizer Hmm. I am not sure the recursion is such a great idea. Could we limit this to the branch of the hierarchy which is terminal? Thus, if the recursion parameter is set to true and the parent OU has a set of children (with no grand children), then we would perform the deletion. 

I am just a bit concerned with situations when entire branches of the hierarchy can be nuked irrevocably by mistake.

**Comment by Bekkalizer** [comment]
I made it because I needed to delete bigger branches in a tree 5 levels deep, deleting branches from level 2 and all the way down. We could make it safer or more explicit with another option called maxrecursionlevels - or requiring the name of the top level orgunit as a parameter, or some other mecanism.

Id anyways say that its not safe to use this script in a production setting with tracker data. The tracked entitity instance data is connected to the orgunit in 3 different levels: trackedentityinstance, programinstance and programstageinstance. For example, if the tracked entity instance was first registered in orgunit A, then has enrollments in orgunit B, and we run this script for deleting everything from orgunit A - we will have to delete the tracked entity instance, all its programisntances(even those that happened in B), and all the programstageinstances below these...

**Comment by jason-p-pickering** [comment]
Good points, and we should probably try and fix this. 

What do you think  about two functions to separate concerns? 

One for removal of the terminal node (i.e. an orgunit with no children) and another for the recursion? 

So like

SELECT * FROM delete_branch('XXXXX'); 

which would figure out how the recursion should be performed?

**Comment by Bekkalizer** [comment]
Thats a good idea. Suggest we add a separate function in the same file - so we can hopefully avoid the maintenance of having two scripts. The separate function only doing the recursion, and using the delete_site_with_data to actually delete the root nodes one by one.

**Comment by jason-p-pickering** [comment]
Cool. I would suggest maybe that we determine all descendants of the branch, store these in a temp table,  and start deleting  with (delete_site_with_data) from the lowest level and progressing upwards.

**Pull request closed without merging**
